### ISSUE TITLE
Cross-platform binaries: Linux

### ISSUE THREAD

**Issue by kmturley** [Archie3d/aeolus_plugin#12]
Have you published a working Linux binary?

I would like to list your plugin on my site:
https://studiorack.github.io/studiorack-site/

However for that I need Mac, Linux and Windows binaries created!

**Comment by Archie3d** [comment]
Hi, no, I do not publish Linux binaries, only Windows and macOS (VST, VST3, AU, and standalone).
However it is very easy to build for Linux as well. What format do you assume? VST3, LV2? Also what target: x86_64, aarch64?..

**Comment by Archie3d** [comment]
I've tweaked the action on master a bit (after the merge) to clean up the artefacts and also include the AU for macOS.
Thanks for the contribution!

**Comment by kmturley** [comment]
No problem! If you wanted to take automation a step further you can create a `release.yml` something like this:

```
name: Release Aeolus plugin

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  type: Release
  dir_build: ./build
  dir_source: .

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_id: ${{ steps.draft_release.outputs.id }}
      upload_url: ${{ steps.draft_release.outputs.upload_url }}
    steps:
      - name: Draft release
        id: draft_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true

  build_release:
    name: Build release
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        include:
          - os: ubuntu-latest
            name: linux
            generator: Unix Makefiles
            path: ./build/Aeolus_artefacts
          - os: macos-latest
            name: mac
            generator: Unix Makefiles
            path: ./build/Aeolus_artefacts
          - os: windows-2019
            name: win
            generator: Visual Studio 16 2019
            path: ./build/Aeolus_artefacts/Release

    steps:
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install ninja-build libx11-dev libfreetype-dev libasound2-dev libxrandr-dev libxinerama-dev libxcursor-dev

    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: brew install ninja

    - name: Install Windows dependencies
      if: matrix.os == 'windows-2019'
      run: choco install ninja

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build plugin
      run: |
        cmake \
          -G "${{ matrix.generator }}" \
          -DWITH_ASIO=OFF \
          -S "${{ env.dir_source }}" \
          -B "${{ env.dir_build }}"
        cmake --build "${{ env.dir_build }}" --config "${{ env.type }}"

    - name: List errors
      run: cat "${{ env.dir_build }}/CMakeFiles/CMakeError.log" || true

    - name: List files generated
      run: |
        cd ${{ matrix.path }}
        find "$(pwd)"

    - name: Compress plugin
      run: |
        cd "${{ env.dir_build }}/${{ env.type }}"
        7z a ../aeolus-${{ matrix.name }}.zip -r

    - name: Upload plugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ${{ inputs.dir_build }}/aeolus-${{ matrix.name }}.zip
        asset_name: aeolus-${{ matrix.name }}.zip
        asset_content_type: application/zip

  publish_release:
    name: Publish release
    needs: [create_release, build_release]
    runs-on: ubuntu-latest
    steps:
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.create_release.outputs.upload_id }}
```

Then when you tag your repo, it would build and create a release automatically!
```
git tag v0.0.1
git push && git push origin --tags
```
